In [1]:
print("Hello World")


Hello World


In [2]:
!pip3 install numpy

# #we are going to learn numpy

In [3]:
import numpy as np

In [4]:
arr = np.array ([[ 1, 2 , 3],
                [4 , 2 , 5]])

In [5]:
type (arr)

numpy.ndarray

In [6]:
arr.ndim

2

In [7]:
arr.shape

(2, 3)

In [8]:
arr.size

6

In [9]:
arr.dtype

dtype('int32')

In [10]:
#creating array from list with type float
a = np.array([[1 , 2 , 4] , [5 , 5 , 6] , [8, 9 ,7]] , dtype = 'float')
print ("Array ceated using passed list :\n", a)

Array ceated using passed list :
 [[1. 2. 4.]
 [5. 5. 6.]
 [8. 9. 7.]]


In [11]:
np.ones ((3 , 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.arange?

In [14]:
f = np.arange(0,30,5)
print ("\n Sequential array with step of 5 :\n", f)

g = np.linspace(0,5,10)
print ("\n Sequential array with 10 vlaues btween 0 and 5:\n" , g)


 Sequential array with step of 5 :
 [ 0  5 10 15 20 25]

 Sequential array with 10 vlaues btween 0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [15]:
arr = np.array ([[1 , 2, 3, 4],
                 [5 , 4 , 6, 7],
                 [1, 45, 67 ,89]])
newarr = arr.reshape(2,2, 3)

In [16]:
newarr

array([[[ 1,  2,  3],
        [ 4,  5,  4]],

       [[ 6,  7,  1],
        [45, 67, 89]]])

In [17]:
arr = np.array([[1 , -1, 2 ,5.0 ],
               [3, 4.8 ,-3, 7],
               [4, 9.0 , -34 , 67],
               [34, 67, 6.8 , 43]])


In [18]:
arr


array([[  1. ,  -1. ,   2. ,   5. ],
       [  3. ,   4.8,  -3. ,   7. ],
       [  4. ,   9. , -34. ,  67. ],
       [ 34. ,  67. ,   6.8,  43. ]])

In [19]:
arr[ 1: , :3]

array([[  3. ,   4.8,  -3. ],
       [  4. ,   9. , -34. ],
       [ 34. ,  67. ,   6.8]])

In [20]:
arr[1::2,:3:2]

array([[ 3. , -3. ],
       [34. ,  6.8]])

In [21]:
#arr[starting index :end+1 : step size , starting index : end+1: step size]  #[row , col]

In [22]:
a = np.array ([1,2 ,3 ,4]) #broad casting  feature

In [23]:
a

array([1, 2, 3, 4])

In [24]:
a+1

array([2, 3, 4, 5])

In [25]:
#transpose of an array

In [26]:
a = np.array ([[ 1 , 2 , 31] , [2, 6 , 7], [8 , 9 , 10]])

In [27]:
a

array([[ 1,  2, 31],
       [ 2,  6,  7],
       [ 8,  9, 10]])

In [28]:
a.T

array([[ 1,  2,  8],
       [ 2,  6,  9],
       [31,  7, 10]])

In [29]:
a.max() #printing the maximum ele of array

31

In [30]:
print ("printing the maximum ele acc to row wise :", a.max(axis = 1))

printing the maximum ele acc to row wise : [31  7 10]


In [31]:
print ("colwise minimum ele:", a.min(axis = 0))

colwise minimum ele: [1 2 7]


In [32]:
print ("sum of all array ele :", a.sum()) 

sum of all array ele : 76


In [34]:
print ("Cumulative sum along each row:\n", a.cumsum(axis = 1))

Cumulative sum along each row:
 [[ 1  3 34]
 [ 2  8 15]
 [ 8 17 27]]


# Operations on matrix

In [35]:
a = np .array([[1 , 2],
              [3 , 4]])
b = np.array([[4, 3],
             [2, 1]])

#add array
print("Array sum : \n", a + b)

#multiply arrays (elementwise multiplication)
print("Array multiplication : \n", a * b)

#matrix multiplication
print("Matrix multiplication : \n", a.dot(b))

Array sum : 
 [[5 5]
 [5 5]]
Array multiplication : 
 [[4 6]
 [6 4]]
Matrix multiplication : 
 [[ 8  5]
 [20 13]]


In [36]:
#create an array of sine values
a = np.array([0, np.pi/2, np.pi])
print("Sine values of array element : ", np.sin(a))

#exponential values
a = np.array([0, 1, 2, 3])
print("Exponent of array elements : ", np.exp(a))

#square root of array values
print("Square root of array elements : ", np.sqrt(a))

Sine values of array element :  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements :  [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements :  [0.         1.         1.41421356 1.73205081]


# Sorting

In [37]:
a = np.array([[1, 4, 2],
             [3, 4, 6],
             [0, -1, 5]])

#sorted array
print("Array elements in sorted order : \n", np.sort(a, axis = None))

#sort array row-wisw
print("Row-wise sorted array : \n", np.sort(a, axis = 1))

#specify sort algorithm
print("Column-wise sort by applying merge sort :\n",np.sort(a, axis = 0, kind = 'mergesort'))



Array elements in sorted order : 
 [-1  0  1  2  3  4  4  5  6]
Row-wise sorted array : 
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
Column-wise sort by applying merge sort :
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]


# Stacking and Splitting

In [42]:
a = np .array([[1 , 2, 10],
              [3 , 4, 77]])
b = np.array([[4, 3, 6],
             [2, 1, 7]])

#vertical stacking
print("Vertical stacking:\n", np.vstack((a, b)))

#horizontal stacking
print("Horizontal stacking:\n", np.hstack((a, b)))

c= [5, 6]

#stacking column
print("\nColumn stacking :\n",np.column_stack((a, c)))

#concatenation method
print("\nConcatenating to 2nd axis :\n", np.concatenate((a, b), 1))

Vertical stacking:
 [[ 1  2 10]
 [ 3  4 77]
 [ 4  3  6]
 [ 2  1  7]]
Horizontal stacking:
 [[ 1  2 10  4  3  6]
 [ 3  4 77  2  1  7]]

Column stacking :
 [[ 1  2 10  5]
 [ 3  4 77  6]]

Concatenating to 2nd axis :
 [[ 1  2 10  4  3  6]
 [ 3  4 77  2  1  7]]


In [44]:
a = np.array ([[1 , 32, 5, 7 ,9 , 11],
              [2 ,4, 6 , 8 , 10 , 12]])

#horizontal splitting 
print("spiltting along horizontal axis into 2 parts : \n", np.hsplit (a, 2))

#vertical splitting 
print ("\n Splitting along vertical axis into 2 parts :\n", np.vsplit(a , 2))


spiltting along horizontal axis into 2 parts : 
 [array([[ 1, 32,  5],
       [ 2,  4,  6]]), array([[ 7,  9, 11],
       [ 8, 10, 12]])]

 Splitting along vertical axis into 2 parts :
 [array([[ 1, 32,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]
